name: release

on:
  release:
    types:
      - created

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all Go dependencies
        run: go get

      - name: Run tests
        run: go test -v -covermode=count ./...

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all Go dependencies
        run: go get

      - name: build
        run: |
          make build-linux
          make build-windows
          make build-macos

      - name: upload artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'bin/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}